services:
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: localuser
      MONGO_INITDB_ROOT_PASSWORD: localpassword
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  node_app:
    image: node:22
    working_dir: /app
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/navigator/node_modules
      - /app/server/node_modules
    depends_on:
      - mongodb
    command: >
      sh -c "npm install --prefix navigator &&
              npm install --prefix server &&
              (npm run dev --prefix navigator -- --host &) &&
              npm run start --prefix server"

volumes:
  db_data:
